language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt --use-mirrors"
env:
  - DB=mysql
before_script:
  - bash main/travis/setup.sh
  - mysql -e 'create database class2go'
script: 
  - cd main; python manage.py test -v 2
notifications:
  irc:
    channels: "irc.freenode.org#class2go-internal"
    on_failure: change
