language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt --use-mirrors"
  # doesn't work, returns with 100, don't know why
  # - "sudo apt-get install google-chrome-stable"
  #
  # jrbl experimenting to try to get selenium tests working
  - sudo apt-get install chromium-browser
  - cd /tmp && curl -O http://chromedriver.googlecode.com/files/chromedriver_linux32_23.0.1240.0.zip && \
    unzip chromedriver_linux32_23.0.1240.0.zip && mv chromedriver /usr/local/bin && cd -
env:
  - DB=mysql
before_script:
  - bash main/travis/setup.sh
  - mysql -e 'create database class2go'
script: 
  # for now don't run selenium tests until we can figure out how 
  - cd main; python manage.py test -v 2 --attr='!selenium'
notifications:
  irc: "irc.freenode.org#class2go-internal"
